# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mandelbrot_service_pb2 as mandelbrot__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mandelbrot_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MandelbrotServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WaitForSignal = channel.unary_stream(
                '/mandelbrot.MandelbrotService/WaitForSignal',
                request_serializer=mandelbrot__service__pb2.SignalRequest.SerializeToString,
                response_deserializer=mandelbrot__service__pb2.SignalResponse.FromString,
                _registered_method=True)
        self.SendSignal = channel.unary_unary(
                '/mandelbrot.MandelbrotService/SendSignal',
                request_serializer=mandelbrot__service__pb2.SignalRequest.SerializeToString,
                response_deserializer=mandelbrot__service__pb2.SignalResponse.FromString,
                _registered_method=True)
        self.ApplyForBlock = channel.unary_unary(
                '/mandelbrot.MandelbrotService/ApplyForBlock',
                request_serializer=mandelbrot__service__pb2.BlockApplyRequest.SerializeToString,
                response_deserializer=mandelbrot__service__pb2.BlockApplyResponse.FromString,
                _registered_method=True)
        self.SendBlockData = channel.unary_unary(
                '/mandelbrot.MandelbrotService/SendBlockData',
                request_serializer=mandelbrot__service__pb2.SomeRequest.SerializeToString,
                response_deserializer=mandelbrot__service__pb2.SignalResponse.FromString,
                _registered_method=True)
        self.RequestBlockData = channel.unary_unary(
                '/mandelbrot.MandelbrotService/RequestBlockData',
                request_serializer=mandelbrot__service__pb2.BlockDataRequest.SerializeToString,
                response_deserializer=mandelbrot__service__pb2.SomeRequest.FromString,
                _registered_method=True)
        self.NotifyTrainingComplete = channel.unary_unary(
                '/mandelbrot.MandelbrotService/NotifyTrainingComplete',
                request_serializer=mandelbrot__service__pb2.TrainingCompleteNotify.SerializeToString,
                response_deserializer=mandelbrot__service__pb2.SignalResponse.FromString,
                _registered_method=True)
        self.SyncStep = channel.unary_unary(
                '/mandelbrot.MandelbrotService/SyncStep',
                request_serializer=mandelbrot__service__pb2.SyncRequest.SerializeToString,
                response_deserializer=mandelbrot__service__pb2.SyncResponse.FromString,
                _registered_method=True)
        self.SyncLayerParameters = channel.unary_unary(
                '/mandelbrot.MandelbrotService/SyncLayerParameters',
                request_serializer=mandelbrot__service__pb2.LayerParameterSyncRequest.SerializeToString,
                response_deserializer=mandelbrot__service__pb2.LayerParameterSyncResponse.FromString,
                _registered_method=True)
        self.GetSyncParameters = channel.unary_unary(
                '/mandelbrot.MandelbrotService/GetSyncParameters',
                request_serializer=mandelbrot__service__pb2.SyncParameterRequest.SerializeToString,
                response_deserializer=mandelbrot__service__pb2.SyncParameterResponse.FromString,
                _registered_method=True)
        self.RegisterAndGetUniqueId = channel.unary_unary(
                '/mandelbrot.MandelbrotService/RegisterAndGetUniqueId',
                request_serializer=mandelbrot__service__pb2.UniqueIdRequest.SerializeToString,
                response_deserializer=mandelbrot__service__pb2.UniqueIdResponse.FromString,
                _registered_method=True)
        self.ReportOomAndWait = channel.unary_unary(
                '/mandelbrot.MandelbrotService/ReportOomAndWait',
                request_serializer=mandelbrot__service__pb2.OomReportRequest.SerializeToString,
                response_deserializer=mandelbrot__service__pb2.OomReportResponse.FromString,
                _registered_method=True)
        self.ClearGradientCache = channel.unary_unary(
                '/mandelbrot.MandelbrotService/ClearGradientCache',
                request_serializer=mandelbrot__service__pb2.ClearGradientCacheRequest.SerializeToString,
                response_deserializer=mandelbrot__service__pb2.ClearGradientCacheResponse.FromString,
                _registered_method=True)


class MandelbrotServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WaitForSignal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendSignal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyForBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendBlockData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestBlockData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyTrainingComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncLayerParameters(self, request, context):
        """Added: Methods related to Layer parameter synchronization.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSyncParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAndGetUniqueId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportOomAndWait(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearGradientCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MandelbrotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WaitForSignal': grpc.unary_stream_rpc_method_handler(
                    servicer.WaitForSignal,
                    request_deserializer=mandelbrot__service__pb2.SignalRequest.FromString,
                    response_serializer=mandelbrot__service__pb2.SignalResponse.SerializeToString,
            ),
            'SendSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSignal,
                    request_deserializer=mandelbrot__service__pb2.SignalRequest.FromString,
                    response_serializer=mandelbrot__service__pb2.SignalResponse.SerializeToString,
            ),
            'ApplyForBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyForBlock,
                    request_deserializer=mandelbrot__service__pb2.BlockApplyRequest.FromString,
                    response_serializer=mandelbrot__service__pb2.BlockApplyResponse.SerializeToString,
            ),
            'SendBlockData': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBlockData,
                    request_deserializer=mandelbrot__service__pb2.SomeRequest.FromString,
                    response_serializer=mandelbrot__service__pb2.SignalResponse.SerializeToString,
            ),
            'RequestBlockData': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestBlockData,
                    request_deserializer=mandelbrot__service__pb2.BlockDataRequest.FromString,
                    response_serializer=mandelbrot__service__pb2.SomeRequest.SerializeToString,
            ),
            'NotifyTrainingComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyTrainingComplete,
                    request_deserializer=mandelbrot__service__pb2.TrainingCompleteNotify.FromString,
                    response_serializer=mandelbrot__service__pb2.SignalResponse.SerializeToString,
            ),
            'SyncStep': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncStep,
                    request_deserializer=mandelbrot__service__pb2.SyncRequest.FromString,
                    response_serializer=mandelbrot__service__pb2.SyncResponse.SerializeToString,
            ),
            'SyncLayerParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncLayerParameters,
                    request_deserializer=mandelbrot__service__pb2.LayerParameterSyncRequest.FromString,
                    response_serializer=mandelbrot__service__pb2.LayerParameterSyncResponse.SerializeToString,
            ),
            'GetSyncParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSyncParameters,
                    request_deserializer=mandelbrot__service__pb2.SyncParameterRequest.FromString,
                    response_serializer=mandelbrot__service__pb2.SyncParameterResponse.SerializeToString,
            ),
            'RegisterAndGetUniqueId': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAndGetUniqueId,
                    request_deserializer=mandelbrot__service__pb2.UniqueIdRequest.FromString,
                    response_serializer=mandelbrot__service__pb2.UniqueIdResponse.SerializeToString,
            ),
            'ReportOomAndWait': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportOomAndWait,
                    request_deserializer=mandelbrot__service__pb2.OomReportRequest.FromString,
                    response_serializer=mandelbrot__service__pb2.OomReportResponse.SerializeToString,
            ),
            'ClearGradientCache': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearGradientCache,
                    request_deserializer=mandelbrot__service__pb2.ClearGradientCacheRequest.FromString,
                    response_serializer=mandelbrot__service__pb2.ClearGradientCacheResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mandelbrot.MandelbrotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mandelbrot.MandelbrotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MandelbrotService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WaitForSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mandelbrot.MandelbrotService/WaitForSignal',
            mandelbrot__service__pb2.SignalRequest.SerializeToString,
            mandelbrot__service__pb2.SignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mandelbrot.MandelbrotService/SendSignal',
            mandelbrot__service__pb2.SignalRequest.SerializeToString,
            mandelbrot__service__pb2.SignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyForBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mandelbrot.MandelbrotService/ApplyForBlock',
            mandelbrot__service__pb2.BlockApplyRequest.SerializeToString,
            mandelbrot__service__pb2.BlockApplyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendBlockData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mandelbrot.MandelbrotService/SendBlockData',
            mandelbrot__service__pb2.SomeRequest.SerializeToString,
            mandelbrot__service__pb2.SignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestBlockData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mandelbrot.MandelbrotService/RequestBlockData',
            mandelbrot__service__pb2.BlockDataRequest.SerializeToString,
            mandelbrot__service__pb2.SomeRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotifyTrainingComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mandelbrot.MandelbrotService/NotifyTrainingComplete',
            mandelbrot__service__pb2.TrainingCompleteNotify.SerializeToString,
            mandelbrot__service__pb2.SignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mandelbrot.MandelbrotService/SyncStep',
            mandelbrot__service__pb2.SyncRequest.SerializeToString,
            mandelbrot__service__pb2.SyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncLayerParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mandelbrot.MandelbrotService/SyncLayerParameters',
            mandelbrot__service__pb2.LayerParameterSyncRequest.SerializeToString,
            mandelbrot__service__pb2.LayerParameterSyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSyncParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mandelbrot.MandelbrotService/GetSyncParameters',
            mandelbrot__service__pb2.SyncParameterRequest.SerializeToString,
            mandelbrot__service__pb2.SyncParameterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterAndGetUniqueId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mandelbrot.MandelbrotService/RegisterAndGetUniqueId',
            mandelbrot__service__pb2.UniqueIdRequest.SerializeToString,
            mandelbrot__service__pb2.UniqueIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportOomAndWait(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mandelbrot.MandelbrotService/ReportOomAndWait',
            mandelbrot__service__pb2.OomReportRequest.SerializeToString,
            mandelbrot__service__pb2.OomReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearGradientCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mandelbrot.MandelbrotService/ClearGradientCache',
            mandelbrot__service__pb2.ClearGradientCacheRequest.SerializeToString,
            mandelbrot__service__pb2.ClearGradientCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
